- hosts: fs-ga
  tasks:
        - name: show interfaces
          command: ifconfig -a
          register: interfaces

        - name: show results
          debug:
            msg: "{{ interfaces['stdout'] | regex_findall('RX packets:([0-9]+)')  | map('int') | sum }}"
