- hosts: fs-ga
  tasks:
        - name: show root dir
          command: ls -l /
          register: dir1

        - name: show results
          debug: # debug module
            msg: "{{ dir1 }}"

# end
